better exec

diff --git a/.dot/shellrc b/.dot/shellrc
--- a/.dot/shellrc
+++ b/.dot/shellrc
@@ -1,8 +1,16 @@
 #!/usr/bin/env bash
 
-RUNNING_SHELL=${RUNNING_SHELL:=$(basename "${SHELL}")}
+# Check for HOMEBREW INSTALLED BASH
+# NOTE: We always want bash
+echo "${0}" | grep -q zsh &&
+  SHELL="$(which bash)" &&
+  RUNNING_SHELL="bash" &&
+  export SHELL RUNNING_SHELL &&
+  exec env bash
+
+RUNNING_SHELL="${RUNNING_SHELL:="$(basename "${SHELL}")"}"
+RUNNING_OS="${RUNNING_OS:="$(uname -s)"}"
 DOT_HOME="${HOME}/.dot"
-RUNNING_OS="$(uname -s)"
 
 function sourceIt() {
   if [ -z "${1}" ]; then
@@ -17,65 +25,6 @@ function addToPath() {
     export PATH="${1}${PATH:+:${PATH}}"
   fi
 }
-
-addToPath "${DOT_HOME}/bin/scripts"
-addToPath "${HOME}/.local/bin"
-
-case "${RUNNING_SHELL}" in
-bash)
-  export BASH_SILENCE_DEPRECATION_WARNING=1
-
-  # ================================== history ===================================
-  # https://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows
-  export HISTSIZE=9000
-  export HISTFILESIZE="${HISTSIZE}"
-  export HISTCONTROL=ignorespace:ignoredups
-
-  _bash_history_sync() {
-    builtin history -a         #1
-    HISTFILESIZE="${HISTSIZE}" #2
-    builtin history -c         #3
-    builtin history -r         #4
-  }
-
-  history() { #5
-    _bash_history_sync
-    builtin history "$@"
-  }
-  PROMPT_COMMAND=_bash_history_sync
-  ## reedit a history substitution line if it failed
-  shopt -s histreedit
-  ## edit a recalled history line before executing
-  shopt -s histverify
-
-  shopt -s extglob
-
-  [[ $- == *i* ]] &&
-    bind '"\e[A": history-search-backward' &&
-    bind '"\e[B": history-search-forward'
-
-  export PS1="\[\033[0;36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\W/\[\e[34;1m\]\[\e[32;1m\]\$(command -v git > /dev/null 2>&1 && git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/') \[\e[0m\]\$ "
-  ;;
-zsh)
-  export RUNNING_SHELL=bash && exec bash
-  export ZSH_DISABLE_COMPFIX="true"
-  export ZSH="${HOME}/.oh-my-zsh"
-  ZSH_THEME="af-magic"
-  plugins=(
-    git
-  )
-  sourceIt "${ZSH}/oh-my-zsh.sh"
-  ;;
-*)
-  echo "${RUNNING_SHELL} is not configured."
-  ;;
-esac
-
-# ==================================== fzf =====================================
-if [[ $- == *i* ]] && which fzf >/dev/null 2>&1; then
-  sourceIt "${DOT_HOME}/fzf_scripts/completion.${RUNNING_SHELL}" 2>/dev/null
-  sourceIt "${DOT_HOME}/fzf_scripts/key-bindings.${RUNNING_SHELL}" 2>/dev/null
-fi
 
 case "${RUNNING_OS}" in
 Darwin)
@@ -131,9 +80,67 @@ Linux)
   #   find /usr/lib/jvm -maxdepth 6 -type f -executable -name javac 2>/dev/null | sort | head -n 1 | sed 's|/bin.*||' | xargs -I {} ln -sfn {} "${HOME}/.java_home"
   ;;
 *)
-  echo "${RUNNING_OS} is not configured."
+  echo "${RUNNING_OS} is not configured." >&2
   ;;
 esac
+
+addToPath "${HOME}/.local/bin"
+addToPath "${DOT_HOME}/bin/scripts"
+
+case "${RUNNING_SHELL}" in
+zsh)
+  export ZSH_DISABLE_COMPFIX="true"
+  export ZSH="${HOME}/.oh-my-zsh"
+  ZSH_THEME="af-magic"
+  plugins=(
+    git
+  )
+  sourceIt "${ZSH}/oh-my-zsh.sh"
+  ;;
+bash)
+  export BASH_SILENCE_DEPRECATION_WARNING=1
+
+  # ================================== history ===================================
+  # https://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows
+  export HISTSIZE=9000
+  export HISTFILESIZE="${HISTSIZE}"
+  export HISTCONTROL=ignorespace:ignoredups
+
+  _bash_history_sync() {
+    builtin history -a         #1
+    HISTFILESIZE="${HISTSIZE}" #2
+    builtin history -c         #3
+    builtin history -r         #4
+  }
+
+  history() { #5
+    _bash_history_sync
+    builtin history "$@"
+  }
+  PROMPT_COMMAND=_bash_history_sync
+  ## reedit a history substitution line if it failed
+  shopt -s histreedit
+  ## edit a recalled history line before executing
+  shopt -s histverify
+
+  shopt -s extglob
+
+  [[ $- == *i* ]] &&
+    bind '"\e[A": history-search-backward' &&
+    bind '"\e[B": history-search-forward'
+
+  export PS1="\[\033[0;36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\W/\[\e[34;1m\]\[\e[32;1m\]\$(command -v git > /dev/null 2>&1 && git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/') \[\e[0m\]\$ "
+  ;;
+*)
+  echo "${RUNNING_SHELL} is not configured." >&2
+  ;;
+esac
+
+# ==================================== fzf =====================================
+if [[ $- == *i* ]] && which fzf >/dev/null 2>&1; then
+  sourceIt "${DOT_HOME}/fzf_scripts/completion.${RUNNING_SHELL}" 2>/dev/null
+  sourceIt "${DOT_HOME}/fzf_scripts/key-bindings.${RUNNING_SHELL}" 2>/dev/null
+fi
 
 # ==================================== ssh =====================================
 #SSH SCP Aliases
